project:
  type: book
  output-dir: docs

book:
  title: "R Training"
  author: "Matt Green"
  #date: 01/23/2023
  #date-format: "dddd D MMM YYYY [at] HH[:]mm[:]ss"

  chapters:
    - index.qmd
    - exercises.qmd

format:
  html:
    theme: 
      light: cosmo
      dark: [cosmo, theme-dark.scss]

callout-appearance: default
callout-collapse: true
