# About {.unnumbered}

This is training in R, for the winter 2023 cohort.  
Last compiled `r format(Sys.time(), '%A %d %B %Y at %X')`

|           | Tuba | Irem | Inga | Thomas |
|:---------:|:----:|:----:|:----:|:------:|
|   Monday  |   y  |   y  |      |    y   |
|  Tuesday  |   y  |   y  |   y  |        |
| Wednesday |   y  |   y  |   y  |    y   |

# Resources
* **Glasgow data analysis books**: [PsyTeachR](https://psyteachr.github.io/)
  * If you don't have experience with other programming languages, start with their introduction to data visualisation, even if data visualisation is not your main goal.
    * An interactive web tutorial is [here](https://psyteachr.github.io/introdataviz/index.html)
    * A published paper is [here](https://osf.io/download/5e64r/)
    * Data and code can be downloaded [here](https://osf.io/bj83f/)
  * More detailed treatments of the R language, Rmarkdown, and data wrangling can be found in other books that are part of PsyTeachR. Look through the chapter listings of the following 2 books - the first is a shorter treatment:
    * 'Data Skills' [here](https://psyteachr.github.io/data-skills-v1/)
    * 'Applied Data Skills' [here](https://psyteachr.github.io/ads-v2/)
* **Hadley Wickham's R For Data Science book**
  * If you have experience with other languages, and if you can make sense of the Introduction to Data Visualisation above, then you might get most out of following this approach. This is a definitive guide to data wrangling, written by the same people who wrote the code itself. 
    * The textbook is online [here](https://r4ds.had.co.nz/) 
    * Solutions to the exercises in the book are [here](https://jrnold.github.io/r4ds-exercise-solutions/)

# Topics for individuals

## Thomas:
* eye movements in reading: modify supplied code at:
  * [github R code for analysing scanpaths in reading](https://github.com/tmalsburg/scanpath)
* Markdown: 
  * [https://psyteachr.github.io/data-skills-v1/ref1.html#activity-3-open-and-save-a-new-r-markdown-document](https://psyteachr.github.io/data-skills-v1/ref1.html#activity-3-open-and-save-a-new-r-markdown-document)
* Wrangling: 
  * [Glasgow Data Skills book, wrangling section](https://psyteachr.github.io/data-skills-v1/data-wrangling-1.html)
  
## Irem
* Various options:
  * Start with IntroDataViz 
    * [https://psyteachr.github.io/introdataviz/index.html](https://psyteachr.github.io/introdataviz/index.html)
  * Start with Rmarkdown
    * [https://psyteachr.github.io/data-skills-v1/ref1.html#activity-3-open-and-save-a-new-r-markdown-document](https://psyteachr.github.io/data-skills-v1/ref1.html#activity-3-open-and-save-a-new-r-markdown-document)
  * Or continue Glasgow ADS course from `sample()` if you want continuity with last time: 
    * [https://psyteachr.github.io/ads-v2/01-intro.html#arguments](https://psyteachr.github.io/ads-v2/01-intro.html#arguments)
  
## Tuba
* Start with IntroDataViz 
  * [https://psyteachr.github.io/introdataviz/index.html](https://psyteachr.github.io/introdataviz/index.html)
  
## Inga
* some experience with python & matlab
* Start with IntroDataViz but if it's too simple, try Hadley Wickham's book
  * [IntroDataViz](https://psyteachr.github.io/introdataviz/index.html)
  * Hadley Wickham's [book](https://r4ds.had.co.nz/) 
  
